# Generated by Django 3.2.7 on 2021-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210916_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN number of the book.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='The the reviewer has given.'),
        ),
    ]
